version: '3'
services:
  apache:
    build: .docker/apache
    container_name: c_sf4_apache
    ports:
    - 86:80
    volumes:
    - .docker/config/vhosts:/etc/apache2/sites-enabled
    - .:/home/wwwroot/sf4
    depends_on:
    - php

  mysql:
    image: mysql
    container_name: c_sf4_mysql
    volumes:
    - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf4
      MYSQL_USER: sf4
      MYSQL_PASSWORD: sf4
    ports:
    - "8083:3306"

  php:
    build: .docker/php
    container_name: c_sf4_php
    volumes:
    - .:/home/wwwroot/sf4
    depends_on:
    - mysql

  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15673:15672"
      - "5673:5672"
    labels:
      NAME: "rabbitmq1"